name: simple_chips_input
description: The most customizable package containing 2 libraries for creating chips and selecting chips
version: 1.2.2
homepage: https://simplechipsinput.vercel.app
repository: https://github.com/danger-ahead/simple_chips_input
issue_tracker: https://github.com/danger-ahead/simple_chips_input/issues

environment:
  sdk: ">=2.18.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
